---

install:
  installCmd: 'pacman -S --noconfirm'
  pacstrap: >
    base
    linux-hardened
    linux-firmware
    bind
    btrfs-progs
    busybox
    cryptsetup
    dosfstools
    efibootmgr
    inetutils
    less
    mc
    moreutils
    nano
    openssh
    python
    sudo
    mkinitcpio-systemd-tool
    tinyssh
    tinyssh-convert
# bind for dig, host, nslookup
# dosfstools, efibootmgr for EFI
# linux-hardened-headers - bloat for kvm image
# linux-firmware - bloat for kvm image, needed?
### START encrypted system
# busybox
# mc
# mkinitcpio-systemd-tool
# python - for tinyssh-convert
# tinyssh
# tinyssh-convert
### END   encrypted system

  timezone: "Europe/Berlin"

localdomain: "lan"

bootloader:
  timeout: "0"

user:
  - name: user999
    useraddParams: "--groups wheel --create-home --shell /bin/bash --user-group"
    sshKeys: |
      ssh-ed25519 CHANGEME localuser@localhost
    password: 'example'

...
