---

- name: resolve device-path
  shell: "readlink -f {{ part_infos.device }}"
  register: blockdevice_root

- name: Update the system clock
  command: "timedatectl set-ntp true"

- name: Check for uefi firmware
  stat:
    path: /sys/firmware/efi
  register: efiFirmware

...
