---

- block:
  - name: check for cryptdevice
    stat:
      path: '/dev/mapper/{{ storage.partitions.root.label.mapper }}'
    register: cryptdevice
  - name: close cryptdevice
    shell:
      cryptsetup
      luksClose
      {{ storage.partitions.root.label.mapper }}
    when: cryptdevice.stat.exists

- name: encrypt root
  shell:
    bash -c "echo '{{ cryptsetup.password }}' |
    cryptsetup
    luksFormat
    --cipher={{ cryptsetup.cipher }}
    --hash={{ cryptsetup.hash }}
    --key-size={{ cryptsetup.keySize }}
    --batch-mode
    --type={{ cryptsetup.type }}
    {% if cryptsetup.iterTime is defined %}--iter-time={{ cryptsetup.iterTime }}
    {% elif cryptsetup.pbkdfForceIterations %}--pbkdf-force-iterations={{ cryptsetup.pbkdfForceIterations }}
    {% endif %}
    --label={{ storage.partitions.root.label.crypt }}
    /dev/disk/by-partlabel/{{ storage.partitions.root.encrypted.label }}"

- debug:
    msg: "WARNING: opening cryptdevice with --allow-discards!"
  when: partitions.allowDiscards

- name: open root cryptdevice
  shell:
    bash -c "echo '{{ cryptsetup.password }}' |
    cryptsetup
    {% if partitions.allowDiscards %}--allow-discards{% endif %}
    luksOpen
    /dev/disk/by-partlabel/{{ storage.partitions.root.encrypted.label }}
    {{ storage.partitions.root.label.mapper }}"

...
