---

hostname: "archlinux"

cryptsetup:
  ### REMEMBER: iterTime and pbkdfForceIterations CANNOT be used together!
  ### REMEMBER2: iterTime depends on the CPU, so iterTime on one system will be different than on another system.
  password: 'example'
  label: 'root'
  cipher: "aes-xts-plain64"
  hash: "sha512"
  keySize: "512"
  type: "luks2"
  # iterTime: "5000"
  pbkdfMemory: "524288"
  pbkdfParallel: "4"
  pbkdfForceIterations: "10"


part_infos:
  mountPath: "/mnt"
  partitionTable: "gpt"
  device: "sda"
  encrypted: true

  bios:
    alignment: "1"
    partlabel: "biosBoot"
    part_start: "34"
    part_end: "2047"
    number: 10
    type: "0xEF02"

  partitions:
  - partition: "boot"
    alignment: "2048"
    partlabel: "boot"
    part_start: "2M"
    part_end: "+256M"
    number: 1
    type: "0x8300"

    fstype: "ext2"
    fslabel: "bootfs"
    createOpt: "-F -L bootfs"

    bootfs:
      path: "/boot"
      opts: "lazytime"
      #opts: "lazytime,umask=0077" ### umask only with vfat

  - partition: "root"
    alignment: "2048"
    partlabel: "root"
    cryptLabel: "root.encrypted"
    mapperLabel: "root.decrypted"
    part_start: "0"   # <- 0 = min available sector
    part_end:   "0"   # <- 0 = max available sector
    number: 2
    type: "0x8308"

    fstype: "btrfs"
    fslabel: "rootfs"
    createOpt: "-f -L rootfs --csum xxhash"

    rootfs:
      subvol: "@rootfs"
      path: "/"
      opts: "subvol=@rootfs,lazytime,space_cache,autodefrag,compress=zstd:2"
    subvolumes:
    - subvol: "@home"
      path: "/home"
      opts: "subvol=@home,lazytime,space_cache,autodefrag,compress=zstd:2"
    - subvol: "@varcache"
      path: "/var/cache"
      opts: "subvol=@varcache,lazytime,space_cache"
    - subvol: "@varlog"
      path: "/var/log"
      opts: "subvol=@varlog,lazytime,space_cache,autodefrag,compress=zstd:2"

rootDevice: '/dev/mapper/{{ part_infos.partitions[1].mapperLabel }}'

network:
  initrd: |
    [Match]
    Name=eth0

    [Network]
    Address=IPV4/SUBNET
    Gateway=GWIPV4

systemdNetworkd:
  interfaces:
    eno1: "eno1 eth0"
  network:
    eno1: |
      [Match]
      Name=INTERFACE-NAMES

      [Network]
      Address=IPV4/SUBNET
      Gateway=GWIPV4

      #DHCP=ipv6
      Address=IPV6/SUBNET
      #IPv6AcceptRA=true

      #[DHCPv6]
      #DUIDType=link-layer
      #DUIDRawData=SOMEDUID

...
