---

- name: update archlinux-keyring
  shell: '/usr/bin/pacman -Sy --noconfirm archlinux-keyring'

- name: execute pacstrap
  shell: '/usr/bin/pacstrap {{ storage.mountPath }} {{ install.pacstrap }}'

- name: execute partprobe
  shell: '/usr/bin/partprobe /dev/mapper/{{ storage.partitions.root.label.mapper }}'

- name: execute genfstab
  shell: '/usr/bin/genfstab -U {{ storage.mountPath }} >> {{ storage.mountPath }}/etc/fstab'

...
