---

- name: set timezone
  shell: "arch-chroot {{ storage.mountPath }} ln -sf /usr/share/zoneinfo/{{ default.timezone }} /etc/localtime"

- name: execute hwclock
  shell: "arch-chroot {{ storage.mountPath }} hwclock --systohc"
  when: ansible_facts.virtualization_type is not defined

...
