---

- name: set hostname
  copy:
    dest: "{{ storage.mountPath }}/etc/hostname"
    content: "{{ network.hostname }}"

- name: set hosts
  copy:
    dest: "{{ storage.mountPath }}/etc/hosts"
    content: |
      127.0.0.1   localhost
      ::1         localhost
      127.0.1.1   {{ network.hostname }}.{{ network.localdomain }} {{ network.hostname }}

- name: create {{ item.key }}.network file
  copy:
    dest: "{{ storage.mountPath }}/etc/systemd/network/{{ item.key }}.network"
    content: "{{ systemdNetworkd.network[item.key] }}"
  with_dict: "{{ systemdNetworkd.interfaces }}"

- name: create initrd-network
  copy:
    dest: "{{ storage.mountPath }}/etc/mkinitcpio-systemd-tool/network/initrd-network.network"
    content: "{{ network.initrd }}"

- name: enable systemd-networkd
  shell: "arch-chroot {{ storage.mountPath }} systemctl enable systemd-networkd"

...
