---

- name: add users
  command: "arch-chroot {{ part_infos.mountPath }} useradd {{ item.useraddParams }} {{ item.name }}"
  with_items: "{{ user }}"

- name: add user.password
  shell: "/usr/bin/bash -c \"printf '{{ item.password }}\n{{ item.password }}\n'\" | arch-chroot {{ part_infos.mountPath }} passwd {{ item.name }}"
  when: item.password is defined
  with_items: "{{ user }}"

- name: setup sshKeys
  include_tasks: 31-sshKeys.yml
  with_items: "{{ user }}"
  loop_control:
    loop_var: user_loop
    label: "{{ user_loop.name }}"

- name: sshKey and permission for root
  shell: 'arch-chroot {{ part_infos.mountPath }} {{ item }}'
  with_items:
    - 'mkdir -p /root/.ssh/'
    - 'bash -c "echo ''{{ user[0].sshKeys }}'' > /root/.ssh/authorized_keys"'
    - 'find /root -exec chown root: {} \;'
    - 'find /root -type d -exec chmod 0750 {} \;'
    - 'find /root -type f -exec chmod 0640 {} \;'
    - 'ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -N "" -t ed25519'

- name: lock root
  command: "arch-chroot {{ part_infos.mountPath }} passwd -l root"

...
