---

- include_tasks: 61-microcode.yml


- name: Check for uefi firmware
  stat:
    path: /sys/firmware/efi
  register: efiFirmware

- include_tasks: 62-grub.yml
  when: not efiFirmware.stat.exists

- include_tasks: 63-systemd-boot.yml
  when: efiFirmware.stat.exists

...
