---

- name: install both microcodes
  shell: 'arch-chroot {{ part_infos.mountPath }} {{ item }}'
  with_items:
  - '{{ install.installCmd }} amd-ucode'
  - '{{ install.installCmd }} intel-ucode'
  when: ansible_facts.virtualization_type is defined

- name: install microcode for AMD
  command: "arch-chroot {{ part_infos.mountPath }} {{ install.installCmd }} amd-ucode"
  when: ansible_facts.processor.1 == "AuthenticAMD"

- name: install microcode for Intel
  shell: "arch-chroot {{ part_infos.mountPath }} {{ install.installCmd }} intel-ucode"
  when: ansible_facts.processor.1 == "GenuineIntel"

...
