---

- name: install grub
  shell: 'arch-chroot {{ storage.mountPath }} {{ install.cmd }} grub'

- name: replace grub-timeout
  lineinfile:
    path: "{{ storage.mountPath }}/etc/default/grub"
    regexp: '^GRUB_TIMEOUT=\d+'
    line: "GRUB_TIMEOUT={{ default.bootloader.timeout }}"
  notify: regenerate grub.cfg

- name: disable grub-distributor
  lineinfile:
    path: "{{ storage.mountPath }}/etc/default/grub"
    regexp: '^GRUB_DISTRIBUTOR="(.*)"'
    line: '#GRUB_DISTRIBUTOR="\g<1>"'
    backrefs: yes
  notify: regenerate grub.cfg

- name: remove loglevel
  lineinfile:
    path: "{{ storage.mountPath }}/etc/default/grub"
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)(loglevel=\d)?(.*")'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\g<1>\g<3>'
    backrefs: yes
  notify: regenerate grub.cfg

- name: execute grub-install
  shell: arch-chroot {{ storage.mountPath }} grub-install --target=i386-pc /dev/{{ storage.device }}
  notify: regenerate grub.cfg

...
