---

- include_tasks: 10-prep.yml
- include_tasks: 20-setup.yml
- include_tasks: 30-users.yml
- include_tasks: 40-headless.yml
- include_tasks: 50-mkinitramfs.yml
- include_tasks: 60-bootloader.yml
- include_tasks: 70-cleanup.yml

...
